version: "2.1"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - /app/node_modules
      - ./web:/app
    shm_size: "128m"
  auth-service:
    build:
      dockerfile: Dockerfile
      context: ./authorisationservice
    ports:
      - "8080:8080"
    volumes:
      - ./authorisationservice:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hieu
#    healthcheck:
#      test: ["CMD","mysqladmin","ping","-h","localhost"]
#      timeout: 20s
#      retries: 10
#     volumes:
#       - ./MySQL:/docker-entrypoint-initdb.d
