version: "3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - /app/node_modules
      - ./web:/app
    shm_size: "128m"
  auth-service:
    build:
      dockerfile: Dockerfile.dev
      context: ./authorisationservice/demo
    ports:
      - "8080:8080"
    volumes:
      - ./authorisationservice/demo:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql_service
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hieu
    # volumes:
    #   - ./MySQL:/docker-entrypoint-initdb.d
