version: "3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - /app/node_modules
      - ./web:/app
  auth-service:
    build:
      dockerfile: Dockerfile
      context: ./authorisationservice/demo
    volumes: -.:/app
    ports:
      - "8080:8080"
