spring:
  datasource: 
    url: jdbc:mysql://mysql/hieu?allowPublicKeyRetrieval=true&useSSL=false
    username: root 
    password: password
  jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 921545662264-0p53bufc1tfnit0r0ikd4sdk40lou7cv.apps.googleusercontent.com
            clientSecret: 6SkXQ4txQwHwkBnCe9Yexlkz
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
                - email
                - profile
  session:
    store-type: none
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8500/oauth2/redirect